# Generated by Django 5.1.5 on 2025-04-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('product-info', 'Product Information'), ('client-account', 'Client Account'), ('orders', 'Orders'), ('payment', 'Payment'), ('delivery', 'Delivery'), ('contact', 'Contact Us')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
