# Generated by Django 5.1.5 on 2025-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='section',
            field=models.CharField(choices=[('taste-and-treats', 'Tasting & Treats'), ('your-sweet-account', 'Your Sweet Profile'), ('orders', 'Orders'), ('payment', 'Payment'), ('delivery', 'Delivery')], max_length=50),
        ),
    ]
