# Generated by Django 5.1.5 on 2025-03-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
