# Generated by Django 5.1.5 on 2025-03-23 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercontactinfo_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
