# Generated by Django 5.1.5 on 2025-02-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Delivery Configuration',
                'verbose_name_plural': 'Delivery Configurations',
            },
        ),
    ]
