# Generated by Django 5.1.5 on 2025-02-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_deliveryconfig_deliverycosts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryCosts',
            new_name='CheckoutConfig',
        ),
    ]
