# Generated by Django 5.1.5 on 2025-02-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_deliverycosts_checkoutconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutconfig',
            options={'verbose_name': 'Checkout Configuration', 'verbose_name_plural': 'Checkout Configurations'},
        ),
        migrations.AddField(
            model_name='checkoutconfig',
            name='stripe_currency',
            field=models.CharField(default='eur', max_length=3),
        ),
    ]
