# Generated by Django 5.1.5 on 2025-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_shippinginfo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
