# Generated by Django 5.1.5 on 2025-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
