# Generated by Django 5.1.5 on 2025-02-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_stripe_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='grand_total',
        ),
    ]
