# Generated by Django 5.1.5 on 2025-02-15 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_webhookevent_processed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stripe_pid'], name='checkout_or_stripe__55139c_idx'),
        ),
    ]
