# Generated by Django 5.1.5 on 2025-02-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_order_checkout_or_stripe__55139c_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='grand_total',
            new_name='amount_total',
        ),
    ]
