# Generated by Django 5.1.5 on 2025-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_rename_grand_total_order_amount_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_total_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
