# Generated by Django 5.1.5 on 2025-02-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_order_amount_total_cents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_total',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount_total_cents',
            new_name='grand_total_cents',
        ),
    ]
