# Generated by Django 5.1.5 on 2025-03-02 15:30

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_order_delivery_cost_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
