# Generated by Django 5.1.5 on 2025-03-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_alter_shippinginfo_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='full_name',
        ),
    ]
