# Generated by Django 5.1.5 on 2025-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_remove_shippinginfo_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='original_default',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
