# Generated by Django 5.1.5 on 2025-03-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_remove_shippinginfo_original_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='guest_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='guest_first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='guest_last_name',
        ),
    ]
