# Generated by Django 5.1.5 on 2025-03-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_rename_email_order_guest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent',
        ),
    ]
