# Generated by Django 5.1.5 on 2025-03-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0027_shippinginfo_created_at_shippinginfo_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInfo',
        ),
    ]
