# Generated by Django 5.1.5 on 2025-04-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0031_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finalized',
            field=models.BooleanField(default=True),
        ),
    ]
