# Generated by Django 5.1.5 on 2025-04-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0033_remove_order_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finalized',
            field=models.BooleanField(default=True),
        ),
    ]
