# Generated by Django 5.1.5 on 2025-04-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0034_order_is_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
