# Generated by Django 5.1.5 on 2025-04-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0035_alter_order_is_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_finalized',
        ),
    ]
