# Generated by Django 5.1.5 on 2025-04-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_badge',
            field=models.CharField(blank=True, choices=[('spring', 'Spring Special'), ('bestseller', 'Bestseller'), ('new', 'New Arrival')], help_text='Optional badge for featured products', max_length=20, null=True),
        ),
    ]
