# Generated by Django 5.1.5 on 2025-04-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_featured_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
